//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryCo.Business.Components.DeliveryNotificationService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DeliveryInfoStatus", Namespace="http://schemas.datacontract.org/2004/07/BookStore.Services.Interfaces")]
    public enum DeliveryInfoStatus : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Submitted = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderPicked = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OrderInTransit = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Delivered = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DeliveryNotificationService.IDeliveryNotificationService")]
    public interface IDeliveryNotificationService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDeliveryNotificationService/NotifyDeliveryCompletion")]
        void NotifyDeliveryCompletion(System.Guid pDeliverId, DeliveryCo.Business.Components.DeliveryNotificationService.DeliveryInfoStatus status);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IDeliveryNotificationService/NotifyDeliveryCompletion")]
        System.Threading.Tasks.Task NotifyDeliveryCompletionAsync(System.Guid pDeliverId, DeliveryCo.Business.Components.DeliveryNotificationService.DeliveryInfoStatus status);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDeliveryNotificationServiceChannel : DeliveryCo.Business.Components.DeliveryNotificationService.IDeliveryNotificationService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DeliveryNotificationServiceClient : System.ServiceModel.ClientBase<DeliveryCo.Business.Components.DeliveryNotificationService.IDeliveryNotificationService>, DeliveryCo.Business.Components.DeliveryNotificationService.IDeliveryNotificationService {
        
        public DeliveryNotificationServiceClient() {
        }
        
        public DeliveryNotificationServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DeliveryNotificationServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryNotificationServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DeliveryNotificationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void NotifyDeliveryCompletion(System.Guid pDeliverId, DeliveryCo.Business.Components.DeliveryNotificationService.DeliveryInfoStatus status) {
            base.Channel.NotifyDeliveryCompletion(pDeliverId, status);
        }
        
        public System.Threading.Tasks.Task NotifyDeliveryCompletionAsync(System.Guid pDeliverId, DeliveryCo.Business.Components.DeliveryNotificationService.DeliveryInfoStatus status) {
            return base.Channel.NotifyDeliveryCompletionAsync(pDeliverId, status);
        }
    }
}
